spring:
  application:
    name: emsp
  datasource:
    url: jdbc:mysql://13.250.106.33:3306/emsp_db?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useUnicode=true&tinyInt1isBit=false&allowPublicKeyRetrieval=true
    username: root
    password: admin123456
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id


logging:
  level:
    com:
      baomidou:
        mybatisplus: debug